version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb
    environment:
      INFLUXDB_DB: "power"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: ""
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
  alphaess:
    image: alexturner/alphaess
    environment:
      DBURL: "http://influxdb:8086"
      DBUSER: "admin"
      DBPASS: "wombats"
      DBNAME: "test"
      ESSUSER: ""
      ESSPASS: ""
      ESSSN: ""
    container_name: alphaess
    restart: always
    networks:
      - monitoring
networks:
  monitoring:
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
