version: "2"
services:
  alphaess:
    image: alphaess
    environment:
      DBURL: "http://alexturner.co:8086"
      DBUSER: "admin"
      DBPASS: "wombats"
      DBNAME: "test"
      ESSUSER: "garry_turner@me.com"
      ESSPASS: "Wombats##1962"
      ESSSN: "AL4001019010306"
    container_name: alphaess
    restart: always
    networks:
      - monitoring
networks:
  monitoring:
